serviceMaps:
 serviceName: PropertyTax Calculator
 mappings:
 - version: 1.0
   name: pt-calculator
   description: Persists the pt-calculator related records to db
   fromTopic: save-pt-billingslab
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_pt_Billingslab_v2(id, tenantid, propertyType, roadType, constructionType, ward, mohalla, fromDate, toDate, unitRate, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: BillingSlab.*
      jsonMaps:

       - jsonPath: $.BillingSlab.*.id

       - jsonPath: $.BillingSlab.*.tenantId

       - jsonPath: $.BillingSlab.*.propertyType

       - jsonPath: $.BillingSlab.*.roadType

       - jsonPath: $.BillingSlab.*.constructionType

       - jsonPath: $.BillingSlab.*.ward

       - jsonPath: $.BillingSlab.*.mohalla

       - jsonPath: $.BillingSlab.*.fromDate

       - jsonPath: $.BillingSlab.*.toDate

       - jsonPath: $.BillingSlab.*.unitRate

       - jsonPath: $.BillingSlab.*.auditDetails.createdBy

       - jsonPath: $.BillingSlab.*.auditDetails.createdTime

       - jsonPath: $.BillingSlab.*.auditDetails.lastModifiedBy

       - jsonPath: $.BillingSlab.*.auditDetails.lastModifiedTime


 - version: 1.0
   name: pt-calculator
   description: Persists the pt-calculator related records to db
   fromTopic: update-pt-billingslab
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_pt_Billingslab_v2 SET propertyType = ?, roadType = ?, constructionType = ?, ward = ?, mohalla = ?, fromDate = ?, toDate = ?, unitRate = ?, createdby = ?, createdtime = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE tenantid=? AND id=?;

      basePath: BillingSlab.*
      jsonMaps:

       - jsonPath: $.BillingSlab.*.propertyType

       - jsonPath: $.BillingSlab.*.roadType

       - jsonPath: $.BillingSlab.*.constructionType

       - jsonPath: $.BillingSlab.*.ward

       - jsonPath: $.BillingSlab.*.mohalla

       - jsonPath: $.BillingSlab.*.fromDate

       - jsonPath: $.BillingSlab.*.toDate

       - jsonPath: $.BillingSlab.*.unitRate

       - jsonPath: $.BillingSlab.*.auditDetails.createdBy

       - jsonPath: $.BillingSlab.*.auditDetails.createdTime

       - jsonPath: $.BillingSlab.*.auditDetails.lastModifiedBy

       - jsonPath: $.BillingSlab.*.auditDetails.lastModifiedTime

       - jsonPath: $.BillingSlab.*.tenantId

       - jsonPath: $.BillingSlab.*.id



 - version: 1.0
   name: pt-calculator
   description: Persists the pt-calculator related records to db
   fromTopic: save-pt-assessment
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_pt_assessment(uuid, tenantId, assessmentNumber, demandId, propertyId, assessmentYear, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: Assessment.*
      jsonMaps:

       - jsonPath: $.Assessment.*.uuid

       - jsonPath: $.Assessment.*.tenantId

       - jsonPath: $.Assessment.*.assessmentNumber

       - jsonPath: $.Assessment.*.demandId

       - jsonPath: $.Assessment.*.propertyId

       - jsonPath: $.Assessment.*.assessmentYear

       - jsonPath: $.Assessment.*.auditDetails.createdBy

       - jsonPath: $.Assessment.*.auditDetails.createdTime

       - jsonPath: $.Assessment.*.auditDetails.lastModifiedBy

       - jsonPath: $.Assessment.*.auditDetails.lastModifiedTime


 - version: 1.0
   name: pt-calculator
   description: Persists the pt-calculator related records to db
   fromTopic: update-pt-assessment
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_pt_assessment SET assessmentNumber = ?, demandId = ?, propertyId = ?, assessmentYear = ?, createdby = ?, createdtime = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE tenantId=? AND uuid=?;

      basePath: Assessment.*
      jsonMaps:

       - jsonPath: $.Assessment.*.assessmentNumber

       - jsonPath: $.Assessment.*.demandId

       - jsonPath: $.Assessment.*.propertyId

       - jsonPath: $.Assessment.*.assessmentYear

       - jsonPath: $.Assessment.*.auditDetails.createdBy

       - jsonPath: $.Assessment.*.auditDetails.createdTime

       - jsonPath: $.Assessment.*.auditDetails.lastModifiedBy

       - jsonPath: $.Assessment.*.auditDetails.lastModifiedTime

       - jsonPath: $.Assessment.*.tenantId

       - jsonPath: $.Assessment.*.uuid
